name: CI
on: [push]
jobs:
  lighthouseci:
    name: Run LH Audit 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1

      - name: install pnpm
        run: npm install -g pnpm

      - name: install lhci
        run: pnpm install && pnpm install -g @lhci/cli@0.8.x

      - name: build
        run: pnpm run build

      - name: run lhci
        run: lhci autorun
